### ISSUE TITLE
getting discord api error 

### ISSUE THREAD

**Issue by DFanso** [rikvik2006/discord-server-joiner#1]
> discord-server-joiner@1.0.0 start D:\Git\discord-server-joiner
> node ./dist/index.js

Tokens: 1
[27/06/2024, 16:43:07] ✅ Logged in as pikachu21416513
❌ There was an error during accept invite
DiscordAPIError: Unknown Message
    at RequestHandler.execute (D:\Git\discord-server-joiner\node_modules\.pnpm\discord.js-selfbot-v13@3.1.3\node_modules\discord.js-selfbot-v13\src\rest\RequestHandler.js:391:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (D:\Git\discord-server-joiner\node_modules\.pnpm\discord.js-selfbot-v13@3.1.3\node_modules\discord.js-selfbot-v13\src\rest\RequestHandler.js:63:14)
    at async Client.acceptInvite (D:\Git\discord-server-joiner\node_modules\.pnpm\discord.js-selfbot-v13@3.1.3\node_modules\discord.js-selfbot-v13\src\client\Client.js:531:18) {
  method: 'post',
  path: '/invites/XKNXgMDN',
  code: 10008,
  httpStatus: 403,
  requestData: {
    json: { session_id: 'bca44cbfedd49c6969aefb2857b60a3b' },
    files: [],
    headers: undefined
  },
  retries: 1,
  captcha: null
}

**Comment by rikvik2006** [comment]
Try to change the `x-super-properties` header in the `createClient` method with a new one.
This is a `x-super-properties` obtained from a Discord Canary client: 
```
eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRGlzY29yZCBDbGllbnQiLCJyZWxlYXNlX2NoYW5uZWwiOiJjYW5hcnkiLCJjbGllbnRfdmVyc2lvbiI6IjEuMC4zOTkiLCJvc192ZXJzaW9uIjoiMTAuMC4yMjYyMiIsIm9zX2FyY2giOiJ4NjQiLCJhcHBfYXJjaCI6Ing2NCIsInN5c3RlbV9sb2NhbGUiOiJpdCIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIGRpc2NvcmQvMS4wLjM5OSBDaHJvbWUvMTI0LjAuNjM2Ny4yNDMgRWxlY3Ryb24vMzAuMS4wIFNhZmFyaS81MzcuMzYiLCJicm93c2VyX3ZlcnNpb24iOiIzMC4xLjAiLCJjbGllbnRfYnVpbGRfbnVtYmVyIjozMDYwOTYsIm5hdGl2ZV9idWlsZF9udW1iZXIiOjQ5MTg4LCJjbGllbnRfZXZlbnRfc291cmNlIjpudWxsLCJkZXNpZ25faWQiOjB9
```
This instead is obtained from a Discord Stable client:
```
eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRGlzY29yZCBDbGllbnQiLCJyZWxlYXNlX2NoYW5uZWwiOiJzdGFibGUiLCJjbGllbnRfdmVyc2lvbiI6IjEuMC45MTUyIiwib3NfdmVyc2lvbiI6IjEwLjAuMjI2MjIiLCJvc19hcmNoIjoieDY0IiwiYXBwX2FyY2giOiJ4NjQiLCJzeXN0ZW1fbG9jYWxlIjoiaXQiLCJicm93c2VyX3VzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBkaXNjb3JkLzEuMC45MTUyIENocm9tZS8xMjQuMC42MzY3LjI0MyBFbGVjdHJvbi8zMC4xLjAgU2FmYXJpLzUzNy4zNiIsImJyb3dzZXJfdmVyc2lvbiI6IjMwLjEuMCIsImNsaWVudF9idWlsZF9udW1iZXIiOjMwNTU3MSwibmF0aXZlX2J1aWxkX251bWJlciI6NDkwNTcsImNsaWVudF9ldmVudF9zb3VyY2UiOm51bGwsImRlc2lnbl9pZCI6MH0=
```

This header is an object that contains the Discord client version and OS specification encoded in Base64.
If you decode one of these strings you will get an object like this:
```json
{
  "os":"Windows",
  "browser":"Discord Client",
  "release_channel":"stable",
  "client_version":"1.0.9152",
  "os_version":"10.0.22622",
  "os_arch":"x64",
  "app_arch":"x64",
  "system_locale":"it",
  "browser_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) discord/1.0.9152 Chrome/124.0.6367.243 Electron/30.1.0 Safari/537.36",
  "browser_version":"30.1.0",
  "client_build_number":305571,
  "native_build_number":49057,
  "client_event_source":null,
  "design_id":0
}
```
You could also try to put your `X-Super-Properties`. To obtain in you need to open the Chrome developers tools with `Ctrl + Shift + I`, go on the `Network` tab and filter only the `Fetch/XHR` request, after this click on a random server or user on Discord. 
![image](https://github.com/rikvik2006/discord-server-joiner/assets/75540124/bab746d6-9919-4074-b74c-720e11f9a9a5)

Then some request called `science` should have appeared, then click on one of them
![image](https://github.com/rikvik2006/discord-server-joiner/assets/75540124/4fd7975a-40a6-4d15-9530-b723c5c1e55a)

Now a panel should have opened, search the `Request Headers` section and at the bottom you should find the `X-Super-Properties` header
![image](https://github.com/rikvik2006/discord-server-joiner/assets/75540124/b2c3bb37-0bc1-430e-8b13-b0da60f7af14)

**Comment by DFanso** [comment]
thank you i will check

**Comment by DFanso** [comment]
still getting that error
